package mybatis.dao;

import java.util.List;
import mybatis.model.ItemLender;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ItemLenderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM_LENDER
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    int insert(ItemLender record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM_LENDER
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    List<ItemLender> selectAll();
}