package mybatis.dao;

import java.util.List;
import mybatis.model.Lender;
import org.mybatis.cdi.Mapper;

@Mapper
public interface LenderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LENDER
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LENDER
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    int insert(Lender record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LENDER
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    Lender selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LENDER
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    List<Lender> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LENDER
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    int updateByPrimaryKey(Lender record);

    List<Lender> getSelectedLenders(Integer itemId);
}