package mybatis.model;

public class ItemLender {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM_LENDER.ITEMS_ID
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    private Integer itemsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM_LENDER.LENDERS_ID
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    private Integer lendersId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM_LENDER.ITEMS_ID
     *
     * @return the value of PUBLIC.ITEM_LENDER.ITEMS_ID
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public Integer getItemsId() {
        return itemsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM_LENDER.ITEMS_ID
     *
     * @param itemsId the value for PUBLIC.ITEM_LENDER.ITEMS_ID
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public void setItemsId(Integer itemsId) {
        this.itemsId = itemsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM_LENDER.LENDERS_ID
     *
     * @return the value of PUBLIC.ITEM_LENDER.LENDERS_ID
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public Integer getLendersId() {
        return lendersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM_LENDER.LENDERS_ID
     *
     * @param lendersId the value for PUBLIC.ITEM_LENDER.LENDERS_ID
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public void setLendersId(Integer lendersId) {
        this.lendersId = lendersId;
    }
}