package mybatis.model;

import java.math.BigDecimal;

public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.ID
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.NAME
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.PRICE
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.LENDER_ID
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    private Integer lenderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.ID
     *
     * @return the value of PUBLIC.ITEM.ID
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.ID
     *
     * @param id the value for PUBLIC.ITEM.ID
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.NAME
     *
     * @return the value of PUBLIC.ITEM.NAME
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.NAME
     *
     * @param name the value for PUBLIC.ITEM.NAME
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.PRICE
     *
     * @return the value of PUBLIC.ITEM.PRICE
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.PRICE
     *
     * @param price the value for PUBLIC.ITEM.PRICE
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.LENDER_ID
     *
     * @return the value of PUBLIC.ITEM.LENDER_ID
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public Integer getLenderId() {
        return lenderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.LENDER_ID
     *
     * @param lenderId the value for PUBLIC.ITEM.LENDER_ID
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public void setLenderId(Integer lenderId) {
        this.lenderId = lenderId;
    }
}