package mybatis.model;

public class Lender {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LENDER.ID
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LENDER.EMAIL
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LENDER.NAME
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LENDER.SURNAME
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    private String surname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LENDER.ID
     *
     * @return the value of PUBLIC.LENDER.ID
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LENDER.ID
     *
     * @param id the value for PUBLIC.LENDER.ID
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LENDER.EMAIL
     *
     * @return the value of PUBLIC.LENDER.EMAIL
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LENDER.EMAIL
     *
     * @param email the value for PUBLIC.LENDER.EMAIL
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LENDER.NAME
     *
     * @return the value of PUBLIC.LENDER.NAME
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LENDER.NAME
     *
     * @param name the value for PUBLIC.LENDER.NAME
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LENDER.SURNAME
     *
     * @return the value of PUBLIC.LENDER.SURNAME
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LENDER.SURNAME
     *
     * @param surname the value for PUBLIC.LENDER.SURNAME
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }
}