package mybatis.model;

public class Lendee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LENDEE.ID
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LENDEE.NAME
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LENDEE.ID
     *
     * @return the value of PUBLIC.LENDEE.ID
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LENDEE.ID
     *
     * @param id the value for PUBLIC.LENDEE.ID
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LENDEE.NAME
     *
     * @return the value of PUBLIC.LENDEE.NAME
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LENDEE.NAME
     *
     * @param name the value for PUBLIC.LENDEE.NAME
     *
     * @mbg.generated Sun Apr 11 10:19:35 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}